version: '3'
services: 
  librespot:
    #image: mmmaxwwwell/librespot
    build: ./
    container_name: librespot
    ports:
      - 5454:5454
      - 5454:5454/udp
    env_file:
      - ./settings.example/librespot.env
    networks:
      - librespot
networks:
  librespot: