version: '3'
services: 
  librespot:
    #image: mmmaxwwwell/librespot
    build: ./
    container_name: librespot
    network_mode: "host"
    env_file:
      - ./settings.example/librespot.env
    volumes:
      - ./appdata/librespot/cache:/var/cache/librespot